### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aaronnz** [AlexSheer/phpbb3.1-STK#16]
[phpBB Debug] PHP Notice: in file [ROOT]/ext/forumpromotion/caramel/event/main_listener.php on line 152: Constant CRML_MY_CASH already defined

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/ext/forumpromotion/caramel/event/main_listener.php
LINE: 152
CALL: define()

FILE: (not given by php)
LINE: (not given by php)
CALL: forumpromotion\caramel\event\main_listener->user_setup()

FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
LINE: 164
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
LINE: 53
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php
LINE: 167
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/phpbb/user.php
LINE: 184
CALL: phpbb\event\dispatcher->trigger_event()

FILE: [ROOT]/stk/index.php
LINE: 23
CALL: phpbb\user->setup()

Click here to reload STK.

**Comment by Galixte** [comment]
Hi,

@aaronnz, on which page anf action ?

@AlexSheer, could you take a look, please ?

**Comment by AlexSheer** [comment]
The problem in extension ext/forumpromotion/caramel
Constant CRML_MY_CASH defined at lesat twice
It is not STK problem.
