### ISSUE TITLE
"Recreate Module Management modules" doesn't work

### ISSUE THREAD

**Issue by Leinad4Mind** [AlexSheer/phpbb3.1-STK#21]
The "Recreate Module Management modules" doesn't work. I've updated a forum 3.0.x with many mods to 3.1.x, and now I wanted to clean the Modules that are not from 3.1.x and it doesn't clean :/

**Comment by AlexSheer** [comment]
Fixed!
https://github.com/AlexSheer/phpbb3.1-STK/commit/cbac467a455371e953ad83ccc801a58acc5f0f19
to clean the Modules  need use SUPPORT TOOLS -> Database Cleaner
