### ISSUE TITLE
SQL QUery Tool Bug on MS SQL

### ISSUE THREAD

**Issue by Leinad4Mind** [AlexSheer/phpbb3.1-STK#23]
I get this error when trying to use the SQL Query tool on a MS SQL database.

Fatal error: Call to undefined function phpbb_remove_remarks() in C:\inetpub\wwwroot\forum.mpw\stk\tools\admin\sql_query.php on line 83
Error 1: Call to undefined function phpbb_remove_remarks() at file C:\inetpub\wwwroot\forum.mpw\stk\tools\admin\sql_query.php line 83

**Comment by AlexSheer** [comment]
Fixed! https://github.com/AlexSheer/phpbb3.1-STK/commit/314b65e8d15635623ac174e1b3f85430043ffece
