### ISSUE TITLE
Error reparsing bbcode

### ISSUE THREAD

**Issue by Leinad4Mind** [AlexSheer/phpbb3.1-STK#25]
When I choose Reparse all bbcodes this error appear:

```
[phpBB Debug] PHP Notice: in file [ROOT]/tools/admin/reparse_bbcode.php on line 288: 
[phpBB Debug] PHP Notice: in file [ROOT]/stk/tools/admin/reparse_bbcode.php on line 288: Undefined variable: sql_forum_where

FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 288
CALL: stk_msg_handler()

FILE: [ROOT]/stk/index.php
LINE: 296
CALL: reparse_bbcode->run_tool()



BACKTRACE

FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 288
CALL: stk_msg_handler()

FILE: [ROOT]/stk/index.php
LINE: 296
CALL: reparse_bbcode->run_tool()
```

Strange fact is that when selecting all foruns, it worked... It begun to run the reparsing, BUT after finish my posts still doesn't have the bbcode reparsed :/
But if I edit the message, the bbcode is well reparsed.

**Comment by AlexSheer** [comment]
Fixed!
https://github.com/AlexSheer/phpbb3.1-STK/commit/d7bfda38027662a72bd3e61b91632e79d63c7b1b#diff-fa3962e701680907e3cd1837c3adc1caR148
