### ISSUE TITLE
config_value bug

### ISSUE THREAD

**Issue by Leinad4Mind** [AlexSheer/phpbb3.1-STK#33]
phpBB Debug] PHP : in file [ROOT]/phpbb/db/driver/driver.php on line 855: SQL ERROR [ mysqli ]

Column 'config_value' cannot be null [1048]

SQL

INSERT INTO phpbb_config (config_name, config_value, is_dynamic) VALUES ('fulltext_postgres_ts_name', NULL, 0)

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/config/db.php
LINE: 161
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/phpbb/config/db.php
LINE: 122
CALL: phpbb\config\db->set_atomic()

FILE: [ROOT]/includes/functions.php
LINE: 162
CALL: phpbb\config\db->set()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_controller.php
LINE: 237
CALL: set_config()

FILE: (not given by php)
LINE: (not given by php)
CALL: database_cleaner_controller->config()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 214
CALL: call_user_func()

FILE: [ROOT]/stk/index.php
LINE: 295
CALL: database_cleaner->run_tool()

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/config/db.php
LINE: 161
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/phpbb/config/db.php
LINE: 122
CALL: phpbb\config\db->set_atomic()

FILE: [ROOT]/includes/functions.php
LINE: 162
CALL: phpbb\config\db->set()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_controller.php
LINE: 237
CALL: set_config()

FILE: (not given by php)
LINE: (not given by php)
CALL: database_cleaner_controller->config()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 214
CALL: call_user_func()

FILE: [ROOT]/stk/index.php
LINE: 295
CALL: database_cleaner->run_tool()

**Comment by Galixte** [comment]
Hi @AlexSheer,

could you take a look, please ?

**Comment by AlexSheer** [comment]
Fixed!
https://github.com/AlexSheer/phpbb3.1-STK/commit/234e0b38a8ce0f85f193719bef8c35e19263ee23#diff-275d0536de66093d9969805bde41273dL216
