### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Leinad4Mind** [AlexSheer/phpbb3.1-STK#39]
I saw this error "This STK version is dedicated to phpBB 3.1.x boards, while your phpBB version is %1$s."

If I use right_install.php gist from 3Di it is able to see all the info correctly. Something seems to be wrong with this stk.

**Comment by AlexSheer** [comment]
Fixed https://github.com/AlexSheer/phpbb3.1-STK/commit/6fb2ff219ed68b56bcb4cde1e97c8512cbeefb4a#diff-f81f3dff36bf04b7a070d642c858e883
